# Generated by Django 5.0.6 on 2024-05-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_borrowing_actual_return"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return",
            field=models.DateField(null=True),
        ),
    ]
