# Generated by Django 5.0.6 on 2024-05-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_borrowing_book_id_alter_borrowing_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="book_id",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="book_id",
            field=models.ManyToManyField(to="catalog.book"),
        ),
    ]
