# Generated by Django 5.0.6 on 2024-06-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
