# Generated by Django 5.0.6 on 2024-07-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_delete_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="book_id",
        ),
        migrations.AlterField(
            model_name="payment",
            name="borrowing_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="catalog.borrowing",
            ),
        ),
        migrations.AddField(
            model_name="borrowing",
            name="book_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.book",
                unique=True,
            ),
        ),
    ]
