# Generated by Django 5.0.6 on 2024-07-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0010_remove_borrowing_book_id_alter_payment_borrowing_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="book_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.book",
            ),
        ),
    ]
