# Generated by Django 5.0.6 on 2024-07-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_borrowing_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(null=True),
        ),
    ]
