# Generated by Django 5.0.6 on 2024-07-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_payment_session_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="book_id",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="book_id",
            field=models.ManyToManyField(null=True, to="catalog.book"),
        ),
    ]
